// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ConfigsController from "./configs_controller.js"
application.register("configs", ConfigsController)

import ReadingListController from "./reading_list_controller.js"
application.register("reading-list", ReadingListController)
console.log(ReadingListController)
